{"name":"Categories","description":"Categories from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:37:13.8040156+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Categories":{"queryId":"914d8a6e-9f51-4fb6-b48a-47424f4a1e13","queryName":"Categories","loadEnabled":true}},"document":"section Section1;\r\nshared Categories = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Categories\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Categories","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Categories.csv"},"attributes":[{"name":"CategoryID","dataType":"int64"},{"name":"CategoryName","dataType":"string"},{"name":"Description","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:02.7501458+00:00","location":"https://wabincuscdsa.blob.core.windows.net:443/2425d4d7-ef32-4304-b80f-f6014d6afa77/Categories.csv?snapshot=2024-01-08T12%3A06%3A02.7365538Z"}]}]}