{"name":"Customers","description":"Customers from the DunderMifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:16:26.7178049+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Customers":{"queryId":"c531ecb2-56d3-469f-b568-73df1a2fa6f1","queryName":"Customers","loadEnabled":true}},"document":"section Section1;\r\nshared Customers = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Customers\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Customers","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Customers.csv"},"attributes":[{"name":"CustomerID","dataType":"int64"},{"name":"CustomerCode","dataType":"string"},{"name":"CompanyName","dataType":"string"},{"name":"ContactName","dataType":"string"},{"name":"ContactTitle","dataType":"string"},{"name":"Address","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Region","dataType":"string"},{"name":"PostalCode","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"Phone","dataType":"string"},{"name":"Fax","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:03.5001602+00:00","location":"https://wabincuscdsa.blob.core.windows.net:443/d5105e69-67ef-43ad-b97c-b0239a70a447/Customers.csv?snapshot=2024-01-08T12%3A06%3A03.4846754Z"}]}]}