{"name":"Employees","description":"Employees from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:17:52.6139683+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Employees":{"queryId":"604dadb7-99a9-4446-a50d-66df23de0894","queryName":"Employees","loadEnabled":true}},"document":"section Section1;\r\nshared Employees = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Employees\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Employees","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Employees.csv"},"attributes":[{"name":"EmployeeID","dataType":"int64"},{"name":"LastName","dataType":"string"},{"name":"FirstName","dataType":"string"},{"name":"MiddleName","dataType":"string"},{"name":"Title","dataType":"string"},{"name":"TitleOfCourtesy","dataType":"string"},{"name":"BirthDate","dataType":"date"},{"name":"HireDate","dataType":"date"},{"name":"TerminationDate","dataType":"date"},{"name":"RehireDate","dataType":"date"},{"name":"Address","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Region","dataType":"string"},{"name":"PostalCode","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"HomePhone","dataType":"string"},{"name":"Extension","dataType":"string"},{"name":"Notes","dataType":"string"},{"name":"ReportsTo","dataType":"int64"},{"name":"PhotoPath","dataType":"string"},{"name":"EmployeeStatusID","dataType":"int64"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:02.2345074+00:00","location":"https://wabincuscdsap1.blob.core.windows.net:443/363dabf4-e32e-44e2-9ca5-355cb41507d8/Employees.csv?snapshot=2024-01-08T12%3A06%3A02.2226567Z"}]}]}