{"name":"EmployeeStatus","description":"EmployeeStatus from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:19:08.8528063+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"EmployeeStatus":{"queryId":"b9722db3-65d6-47cd-aadf-e5154a9eb1e2","queryName":"EmployeeStatus","loadEnabled":true}},"document":"section Section1;\r\nshared EmployeeStatus = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"EmployeeStatus\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"EmployeeStatus","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"EmployeeStatus.csv"},"attributes":[{"name":"StatusID","dataType":"int64"},{"name":"StatusName","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:02.6876427+00:00","location":"https://wabincuscdsa.blob.core.windows.net:443/20a16445-606c-4833-abe2-3b17e30a1ab1/EmployeeStatus.csv?snapshot=2024-01-08T12%3A06%3A02.6595978Z"}]}]}