{"name":"OrderDetails","description":"OrderDetails from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:23:32.1187889+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"OrderDetails":{"queryId":"2fb910fe-0a26-4b2a-9654-44dbc9918df2","queryName":"OrderDetails","loadEnabled":true}},"document":"section Section1;\r\nshared OrderDetails = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"OrderDetails\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"OrderDetails","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"OrderDetails.csv"},"attributes":[{"name":"OrderID","dataType":"int64"},{"name":"ProductID","dataType":"int64"},{"name":"UnitPrice","dataType":"decimal"},{"name":"Quantity","dataType":"int64"},{"name":"Discount","dataType":"double"},{"name":"LineTotal","dataType":"double"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:15.0160626+00:00","location":"https://wabincuscdsap1.blob.core.windows.net:443/3c8b16a4-bc97-4fa6-b3bd-afb975a58c01/OrderDetails.csv?snapshot=2024-01-08T12%3A06%3A15.0128743Z"}]}]}