{"name":"Orders","description":"Orders from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:24:39.1760309+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Orders":{"queryId":"8840be00-2c50-454d-ba42-6d3b8060f99e","queryName":"Orders","loadEnabled":true}},"document":"section Section1;\r\nshared Orders = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Orders\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Orders","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Orders.csv"},"attributes":[{"name":"OrderID","dataType":"int64"},{"name":"CustomerID","dataType":"int64"},{"name":"EmployeeID","dataType":"int64"},{"name":"OrderDate","dataType":"dateTime"},{"name":"RequiredDate","dataType":"dateTime"},{"name":"ShippedDate","dataType":"dateTime"},{"name":"ShipVia","dataType":"int64"},{"name":"Freight","dataType":"decimal"},{"name":"ShipName","dataType":"string"},{"name":"ShipAddress","dataType":"string"},{"name":"ShipCity","dataType":"string"},{"name":"ShipRegion","dataType":"string"},{"name":"ShipPostalCode","dataType":"string"},{"name":"ShipCountry","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:06.0158425+00:00","location":"https://wabincuscdsap1.blob.core.windows.net:443/4f063608-90be-4b35-98c1-6620dc3b6d79/Orders.csv?snapshot=2024-01-08T12%3A06%3A06.0132058Z"}]}]}