{"name":"Products","description":"Products from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:26:14.2275343+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Products":{"queryId":"32fc8e14-363f-4fd2-8202-c38e275e8881","queryName":"Products","loadEnabled":true}},"document":"section Section1;\r\nshared Products = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Products\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Products","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Products.csv"},"attributes":[{"name":"ProductID","dataType":"int64"},{"name":"ProductName","dataType":"string"},{"name":"ProductDescription","dataType":"string"},{"name":"SupplierID","dataType":"int64"},{"name":"CategoryID","dataType":"int64"},{"name":"QuantityPerUnit","dataType":"string"},{"name":"UnitPrice","dataType":"decimal"},{"name":"UnitsInStock","dataType":"int64"},{"name":"UnitsOnOrder","dataType":"int64"},{"name":"ReorderLevel","dataType":"int64"},{"name":"Discontinued","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:04.0782991+00:00","location":"https://wabincuscdsap1.blob.core.windows.net:443/7b9a1b6d-4b1e-4bef-9462-0bd576288072/Products.csv?snapshot=2024-01-08T12%3A06%3A04.0692942Z"}]}]}