{"name":"Regions","description":"Regions from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:28:24.789354+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Regions":{"queryId":"832384c1-1c07-46a4-8fa3-d9967f138fb3","queryName":"Regions","loadEnabled":true}},"document":"section Section1;\r\nshared Regions = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Regions\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Regions","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Regions.csv"},"attributes":[{"name":"RegionID","dataType":"int64"},{"name":"RegionName","dataType":"string"},{"name":"Active","dataType":"boolean"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:02.4063911+00:00","location":"https://wabincuscdsap1.blob.core.windows.net:443/a796895d-7fcf-4829-a440-0fa92f0d31c6/Regions.csv?snapshot=2024-01-08T12%3A06%3A02.3948915Z"}]}]}