{"name":"Shippers","description":"Shippers from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:30:24.9423752+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Shippers":{"queryId":"bf3833db-13df-405c-ae3b-7b1dd36ca00f","queryName":"Shippers","loadEnabled":true}},"document":"section Section1;\r\nshared Shippers = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Shippers\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Shippers","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Shippers.csv"},"attributes":[{"name":"ShipperID","dataType":"int64"},{"name":"CompanyName","dataType":"string"},{"name":"Phone","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:02.8126503+00:00","location":"https://wabincuscdsa.blob.core.windows.net:443/e7cf0059-c869-4df9-bcc4-6d4e0082f3a5/Shippers.csv?snapshot=2024-01-08T12%3A06%3A02.8080835Z"}]}]}