{"name":"Suppliers","description":"Suppliers from the Dunder Mifflin SQL DB","version":"1.0","culture":"en-US","modifiedTime":"2022-09-05T18:31:28.0843574+00:00","ppdf:outputFileFormat":"Csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Suppliers":{"queryId":"ffd7e68f-7a26-48aa-9c4d-ae88067ba288","queryName":"Suppliers","loadEnabled":true}},"document":"section Section1;\r\nshared Suppliers = let\r\n  Source = Sql.Database(\"localhost\", \"DunderMifflin\"),\r\n  Navigation = Source{[Schema = \"dbo\", Item = \"Suppliers\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(Navigation, Table.ColumnsOfType(Navigation, {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"localhost;DunderMifflin","kind":"SQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"a1741936-fff9-466e-9948-c00253341bd5","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Suppliers","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Suppliers.csv"},"attributes":[{"name":"SupplierID","dataType":"int64"},{"name":"CompanyName","dataType":"string"},{"name":"ContactName","dataType":"string"},{"name":"ContactTitle","dataType":"string"},{"name":"Address","dataType":"string"},{"name":"City","dataType":"string"},{"name":"Region","dataType":"string"},{"name":"PostalCode","dataType":"string"},{"name":"Country","dataType":"string"},{"name":"Phone","dataType":"string"},{"name":"Fax","dataType":"string"},{"name":"HomePage","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2024-01-08T12:06:02.9689019+00:00","location":"https://wabincuscdsa.blob.core.windows.net:443/03f260fa-27f6-48f8-ae61-3fc03d429438/Suppliers.csv?snapshot=2024-01-08T12%3A06%3A02.9464360Z"}]}]}